config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :todos
  root to: 'todos#index'
  # Root route
  # Resourceful route for todos
  # Custom route example
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/todo.rb
class Todo < ApplicationRecord
    validates :title, presence: true
    belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :todos, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :authenticate_user!
end

app/controllers/todos_controller.rb
class TodosController < ApplicationController
  before_action :set_todo, only: [:show, :edit, :update, :destroy]
  
    def index
      @todos = current_user.todos.all
    end
  
    def show
       @todo = Todo.find(params[:id])
    end
  
    def new
      @todo = current_user.todos.build
    end
  
    def create
      @todo = current_user.todos.build(todo_params)
      if @todo.save
        redirect_to todo_path(@todo)
      else
        render :new
      end
    end
  
    def edit
    end
  
    def update
      if @todo.update(todo_params)
        redirect_to todo_path(@todo)
      else
        render :edit
      end
    end
  
    def destroy
      @todo.destroy
      redirect_to todos_path
    end
  
    private
  
    def set_todo
      @todo = current_user.todos.find(params[:id])
    end
  
    def todo_params
      params.require(:todo).permit(:title, :description, :completed)
    end
  
    protected
    
    def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up, keys: [:username, :email, :password, :password_confirmation])
    end
  
  end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/todos_helper.rb
module TodosHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>KhushiApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/todos/edit.html.erb
<h2>Edit Todo</h2>

<%= form_with model: @todo do |form| %>
  <%= form.label :title %>
  <%= form.text_field :title %>

  <%= form.label :description %>
  <%= form.text_area :description %>

  <%= form.label :completed %>
  <%= form.check_box :completed %>

  <%= form.submit %>
<% end %>

<%= link_to 'Show', @todo %> |
<%= link_to 'Back to Todos', todos_path %>

app/views/todos/index.html.erb
<style>
body {
  background-image: url('https://www.pixelstalk.net/wp-content/uploads/2016/05/Free-Download-HD-Laptop-Backgrounds.jpg');
  background-repeat: no-repeat;
  background-attachment: fixed;
  background-size: cover; 
  text-align: center;
  }
  ul {
  list-style-type: none;
  margin: 0;
  padding: 0;
  overflow: hidden;
  background-color: #333;
}



li a {
  display: block;
  color: white;
  text-align: center;
  padding: 14px 16px;
  text-decoration: none;
}

lt a:hover:not(.active) {
  background-color: #111;
}

.active {
  background-color: #04AA6D;
}
</style>
<style>
button {
  background-color: red;
  border: none;
  color: black;
  text-align: center;
  text-decoration: none;
  display: inline-block;
  font-size: 16px;
  margin: 2px 2px;
  cursor: pointer;
  padding :10px 8px;
}
</style>

<h1 style="font-size:60px;">Todos App</h1>
<h1>Here you can add your tasks whatever you want to do<h1>
<b>

<ol>
  <% @todos.each do |todo| %>
    <li>
      <%= todo.title %> - <%= todo.description %> 
      <% if todo.completed %>
        <span style="color: green;">...Task Completed</span><button><%= link_to "Remove item", todo, data: {turbo_method: :delete,turbo_confirm: "Are you sure?"} %></button>
      <% else %>
        <span style="color: black;">...Task Incomplete</span><button><%= link_to "Remove item", todo, data: {turbo_method: :delete,turbo_confirm: "Are you sure?"} %></button>
      <% end %>
    </li>
  <% end %>
</ol>
<%= link_to 'New Todo', new_todo_path %>
<%= link_to "log_out", destroy_user_session_path, data: {turbo_method: :delete, turbo_confirm:  "are you sure?"}%>

</b>

app/views/todos/new.html.erb
<h2>New Todo</h2>

<%= form_with model: @todo do |form| %>
  <%= form.label :title %>
  <%= form.text_field :title %>

  <%= form.label :description %>
  <%= form.text_area :description %>

  <%= form.label :completed %>
  <%= form.check_box :completed %>

  <%= form.submit %>
<% end %>

<%= link_to 'Back to Todos', todos_path %>

app/views/todos/show.html.erb
<h2><%= @todo.title %></h2>
<p><%= @todo.description %></p>
<%= link_to 'Edit', edit_todo_path(@todo) %> |
<%= link_to 'Back to Todos', todos_path %>